// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV7Pi3psEvJrucUtg4nxlGiF5oqGjR4eI',
    appId: '1:753456400731:web:8b4d3a2dace751ac39727e',
    messagingSenderId: '753456400731',
    projectId: 'chat-app-devimun',
    authDomain: 'chat-app-devimun.firebaseapp.com',
    storageBucket: 'chat-app-devimun.appspot.com',
    measurementId: 'G-PV656NK266',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW15ahXVpEdBs1dOSdH7l7kyBcyyDUIG0',
    appId: '1:753456400731:android:39e624d2e75d70fc39727e',
    messagingSenderId: '753456400731',
    projectId: 'chat-app-devimun',
    storageBucket: 'chat-app-devimun.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDjlFxXs-4-q_SvhE4wk97yl6WoAXJiac',
    appId: '1:753456400731:ios:39f28b55a833002139727e',
    messagingSenderId: '753456400731',
    projectId: 'chat-app-devimun',
    storageBucket: 'chat-app-devimun.appspot.com',
    iosClientId:
        '753456400731-3u9cqspt63qrlut7eq1qfbes6qnsk38c.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDjlFxXs-4-q_SvhE4wk97yl6WoAXJiac',
    appId: '1:753456400731:ios:e62a7bc666fb3c2339727e',
    messagingSenderId: '753456400731',
    projectId: 'chat-app-devimun',
    storageBucket: 'chat-app-devimun.appspot.com',
    iosClientId:
        '753456400731-sru6cvgsoapgtrkn3n1ce78ll0o8f5hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppWithFirebase.RunnerTests',
  );
}
